### Code Supplement For Task3-4(b)

In [1]:
import numpy as np
from scipy.linalg import eigh

# Step 1: Define the adjacency matrix (A) and the degree matrix (D)
A = np.array([
    [0, 1, 1, 0, 0, 0, 0],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 1, 0, 0, 0],
    [0, 0, 1, 0, 1, 0, 0],
    [0, 0, 0, 1, 0, 1, 1],
    [0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0]
])

D = np.diag(np.sum(A, axis=1))
print("Degree Matrix (D):\n", D)

Degree Matrix (D):
 [[2 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 2 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]


In [2]:
# Step 2: Compute the unnormalized Laplacian (L)
L = D - A
print("\nUnnormalized Laplacian (L):\n", L)


Unnormalized Laplacian (L):
 [[ 2 -1 -1  0  0  0  0]
 [-1  2 -1  0  0  0  0]
 [-1 -1  3 -1  0  0  0]
 [ 0  0 -1  2 -1  0  0]
 [ 0  0  0 -1  3 -1 -1]
 [ 0  0  0  0 -1  1  0]
 [ 0  0  0  0 -1  0  1]]


In [4]:
# Step 3: Compute the normalized Laplacian (L_norm)
D_inv_sqrt = np.diag(1 / np.sqrt(np.diag(D)))
print("\nD_inv_sqrt:\n", D_inv_sqrt)


D_inv_sqrt:
 [[0.70710678 0.         0.         0.         0.         0.
  0.        ]
 [0.         0.70710678 0.         0.         0.         0.
  0.        ]
 [0.         0.         0.57735027 0.         0.         0.
  0.        ]
 [0.         0.         0.         0.70710678 0.         0.
  0.        ]
 [0.         0.         0.         0.         0.57735027 0.
  0.        ]
 [0.         0.         0.         0.         0.         1.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  1.        ]]


In [5]:
L_norm = D_inv_sqrt @ L @ D_inv_sqrt
print("\nNormalized Laplacian (L_norm):\n", L_norm)


Normalized Laplacian (L_norm):
 [[ 1.         -0.5        -0.40824829  0.          0.          0.
   0.        ]
 [-0.5         1.         -0.40824829  0.          0.          0.
   0.        ]
 [-0.40824829 -0.40824829  1.         -0.40824829  0.          0.
   0.        ]
 [ 0.          0.         -0.40824829  1.         -0.40824829  0.
   0.        ]
 [ 0.          0.          0.         -0.40824829  1.         -0.57735027
  -0.57735027]
 [ 0.          0.          0.          0.         -0.57735027  1.
   0.        ]
 [ 0.          0.          0.          0.         -0.57735027  0.
   1.        ]]


In [6]:
# Step 4: Compute eigenvalues and eigenvectors of L_norm
eigvals, eigvecs = eigh(L_norm)
print("Eigenvalues:\n", eigvals)
print("\nEigenvectors:\n", eigvecs)

Eigenvalues:
 [1.11022302e-15 1.49557924e-01 8.70925561e-01 1.00000000e+00
 1.50000000e+00 1.53694039e+00 1.94257612e+00]

Eigenvectors:
 [[-3.77964473e-01 -4.07307600e-01  3.25003362e-01  0.00000000e+00
   7.07106781e-01  2.85748131e-01 -6.29618696e-02]
 [-3.77964473e-01 -4.07307600e-01  3.25003362e-01 -2.45263698e-17
  -7.07106781e-01  2.85748131e-01 -6.29618696e-02]
 [-4.62910050e-01 -3.49634583e-01 -2.95291021e-01  3.00385456e-17
   8.63052134e-15 -7.25793068e-01  2.22480514e-01]
 [-3.77964473e-01  8.62742166e-02 -7.43367856e-01 -1.22631849e-17
  -4.88590621e-15  3.83088547e-01 -3.87746067e-01]
 [-4.62910050e-01  5.29356644e-01  6.02629972e-02 -1.50192728e-17
  -3.05653248e-15  2.21943523e-01  6.72759447e-01]
 [-2.67261242e-01  3.59370978e-01  2.69556529e-01 -7.07106781e-01
   3.27885867e-15 -2.38646885e-01 -4.12081146e-01]
 [-2.67261242e-01  3.59370978e-01  2.69556529e-01  7.07106781e-01
   3.16783636e-15 -2.38646885e-01 -4.12081146e-01]]


In [7]:
# Step 5: Use the Fiedler vector to partition the graph
fiedler_vector = eigvecs[:, 1]  # Second smallest eigenvector
print("\nFiedler Vector (Second Smallest Eigenvector):\n", fiedler_vector)

partition_1 = np.where(fiedler_vector >= 0)[0] + 1  # Nodes in Partition 1
partition_2 = np.where(fiedler_vector < 0)[0] + 1   # Nodes in Partition 2

print("\nPartition 1:", partition_1)
print("Partition 2:", partition_2)


Fiedler Vector (Second Smallest Eigenvector):
 [-0.4073076  -0.4073076  -0.34963458  0.08627422  0.52935664  0.35937098
  0.35937098]

Partition 1: [4 5 6 7]
Partition 2: [1 2 3]
